version: '3.8'

services:
  accounts:
    build: 
      context: ./accounts
      target: accounts-service
    ports:
      - "5000:5000"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=accounts_db
      - DATABASE_URL=postgresql://user:password@db/accounts_db
    depends_on:
      - db

  catalog:
    build: 
      context: ./catalog
      target: catalog-service
    ports:
      - "5001:5001"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=catalog_db
      - DATABASE_URL=postgresql://user:password@db/catalog_db
    depends_on:
      - db

  payments:
    build: 
      context: ./payments
      target: payments-service
    ports:
      - "5002:5002"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=payments_db
      - DATABASE_URL=postgresql://user:password@db/payments_db
    depends_on:
      - db

  publisher:
    build: 
      context: ./publisher
      target: publisher-service
    ports:
      - "5003:5003"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=publisher_db
      - DATABASE_URL=postgresql://user:password@db/publisher_db
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
