version: '3.8'

services:
  accounts-service:
    image: us-central1-docker.pkg.dev/essential-tower-422709-k9/accounts-service/accounts-service:latest
    ports:
      - "8081:8081"
    environment:
      - ENV_VAR=example

  audiobook-service:
    image: us-central1-docker.pkg.dev/essential-tower-422709-k9/audiobook-service/audiobook-service:latest
    ports:
      - "8082:8082"
    environment:
      - ENV_VAR=example

  catalog-service:
    image: us-central1-docker.pkg.dev/essential-tower-422709-k9/catalog-service/catalog-service:latest
    ports:
      - "8083:8083"
    environment:
      - ENV_VAR=example

  payments-service:
    image: us-central1-docker.pkg.dev/essential-tower-422709-k9/payments-service/payments-service:latest
    ports:
      - "8084:8084"
    environment:
      - ENV_VAR=example

  publishers-service:
    image: us-central1-docker.pkg.dev/essential-tower-422709-k9/publishers-service/publishers-service:latest
    ports:
      - "8085:8085"
    environment:
      - ENV_VAR=example
