# prod-accounts-manifest.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: accounts
  template:
    metadata:
      labels:
        app: accounts
    spec:
      containers:
        - name: accounts-container
          image: us-central1-docker.pkg.dev/essential-tower-422709-k9/accounts/accounts:latest
          ports:
          - containerPort: 80
          env:
          - name: ENVIRONMENT
            value: "production"
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: accounts-service
spec:
  selector:
    app: accounts
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: accounts-ingress
spec:
  entryPoints:
    - web
    - websecure
  routes:
  - match: Host(`accounts.storystream.nl`)
    kind: Rule
    services:
    - name: accounts-service
      port: 80
  tls:
    certResolver: letsencrypt
