# prod-catalog-manifest.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
      - name: catalog-container
        image: us-central1-docker.pkg.dev/essential-tower-422709-k9/catalog/catalog:latest
        ports:
        - containerPort: 5000
        envFrom:
          - secretRef:
              name: credentials
        env:
        - name: ENVIRONMENT
          value: "production"
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-service
spec:
  selector:
    app: catalog
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: catalog-ingress
spec:
  entryPoints:
    - web
    - websecure
  routes:
  - match: Host(`catalog.storystream.nl`)
    kind: Rule
    services:
    - name: catalog-service
      port: 5001
  tls:
    certResolver: letsencrypt
