# prod-payments-manifest.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
      - name: payments-container
        image: us-central1-docker.pkg.dev/essential-tower-422709-k9/payments/payment:latest
        ports:
        - containerPort: 80
        env:
        - name: ENVIRONMENT
          value: "production"
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: payments-service
spec:
  selector:
    app: payments
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: payments-ingress
spec:
  entryPoints:
    - web
    - websecure
  routes:
  - match: Host(`payments.storystream.nl`)
    kind: Rule
    services:
    - name: payments-service
      port: 80
  tls:
    certResolver: letsencrypt
