swagger: '2.0'
info:
  title: api-gateway
  description: Sample API on API Gateway with a kubernetes cluster as backend
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /accounts:
    get:
      summary: Accounts microservice for the StoryStream platform
      operationId: accounts
      x-google-backend:
        address: "https://accounts.storystream.nl./accounts"
      responses:
        '200':
          description: A successful response
          schema:
            type: string
      security:
        - auth0_jwk: []
  /payments:
    get:
      summary: Payments microservice for the StoryStream platform
      operationId: payments
      x-google-backend:
        address: "https://payments.storystream.nl"
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        '200':
          description: A successful response
          schema:
            type: string
      security:
        - auth0_jwk: []
  /audiobooks:
    post:
      summary: Publishers microservice for the StoryStream platform
      operationId: publishers
      x-google-backend:
        address: "https://publishers.storystream.nl/"
      responses:
        '200':
          description: A successful response
          schema:
            type: string
        '201':
          description: A successful response
          schema:
            type: string
      security:
        - auth0_jwk: []
  /catalog:
    post:
      summary: Publishers microservice for the StoryStream platform
      operationId: catalog
      x-google-backend:
        address: "https://catalog.storystream.nl/audiobooks"
      responses:
        '200':
          description: A successful response
          schema:
            type: string
        '201':
          description: A successful response
          schema:
            type: string
      security:
        - auth0_jwk: []

  /echo:
    get:
      summary: test url
      operationId: echo
      x-google-backend:
        address: "https://echo.ehv.tjeerdsma.eu/"
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        '200':
          description: A successful response
          schema:
            type: string
      security:
        - auth0_jwk: []


securityDefinitions:
  auth0_jwk:
    authorizationUrl: ""
    flow: "implicit"
    type: "oauth2"
    x-google-issuer: "https://storystream-jads.eu.auth0.com/"
    x-google-jwks_uri: "https://storystream-jads.eu.auth0.com/.well-known/jwks.json"
    x-google-audiences: "AbaMPBs6WVn86TY8Nj17dImhw00OKaFC"
