swagger: '2.0'
info:
  title: api-gateway
  description: Sample API on API Gateway with a kubernetes cluster as backend
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /catalog/{proxy+}:
    get:
      summary: Accounts microservice for the StoryStream platform
      operationId: catalog
      x-google-backend:
        address: "https://catalog.storystream.nl"
      responses:
        '200':
          description: A successful response
          schema:
            type: string
      security:
        - auth0_jwk: []
  /accounts/{proxy+}:
    get:
      summary: Accounts microservice for the StoryStream platform
      operationId: accounts
      x-google-backend:
        address: "https://accounts.storystream.nl"
      responses:
        '200':
          description: A successful response
          schema:
            type: string
      security:
        - auth0_jwk: []
  /payments/{proxy+}:
    get:
      summary: Payments microservice for the StoryStream platform
      operationId: payments
      x-google-backend:
        address: "https://payments.storystream.nl"
      responses:
        '200':
          description: A successful response
          schema:
            type: string
      security:
        - auth0_jwk: []
  /publishers/{proxy+}:
    get:
      summary: Publishers microservice for the StoryStream platform
      operationId: publishers
      x-google-backend:
        address: "https://publishers.storystream.nl"
      responses:
        '200':
          description: A successful response
          schema:
            type: string
      security:
        - auth0_jwk: []

  /echo:
    get:
      summary: test url
      operationId: echo
      x-google-backend:
        address: "https://echo.ehv.tjeerdsma.eu/"
      responses:
        '200':
          description: A successful response
          schema:
            type: string
      security:
        - auth0_jwk: []


securityDefinitions:
  auth0_jwk:
    authorizationUrl: ""
    flow: "implicit"
    type: "oauth2"
    x-google-issuer: "https://storystream-jads.eu.auth0.com/"
    x-google-jwks_uri: "https://storystream-jads.eu.auth0.com/.well-known/jwks.json"
    x-google-audiences: "AbaMPBs6WVn86TY8Nj17dImhw00OKaFC"
