service:
  spec:
    loadBalancerIP: "34.141.168.96"

persistence:
  enabled: true
  path: /data
  size: 1Gi

# better to use cert-manager but not required for this POC
# do not do this in production
deployment:
  initContainers:
    - name: volume-permissions
      image: busybox:latest
      command: ["sh", "-c", "touch /data/acme.json; chown 65532 /data/acme.json; chmod -v 600 /data/acme.json"]
      securityContext:
          runAsNonRoot: false
          runAsGroup: 0
          runAsUser: 0
      volumeMounts:
        - name: data
          mountPath: /data

additionalArguments:
  - "--log.level=INFO"
  - "--global.checknewversion=false"
  - "--global.sendanonymoususage=false"
  - "--entrypoints.websecure.http.tls.domains[0].main=storystream.nl"
  - "--entrypoints.websecure.http.tls.domains[0].sans=*.storystream.nl"
  - "--providers.kubernetesingress=true"
  - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
  - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
  - "--certificatesresolvers.letsencrypt.acme.caserver=https://acme-v02.api.letsencrypt.org/directory"
  - "--certificatesresolvers.letsencrypt.acme.storage=/data/acme.json"
  - "--certificatesresolvers.letsencrypt.acme.email=hessel@tjeerdsma.eu"
